version: '2'
services:
  php:
    build: ./php-fpm
    volumes:
      - ./../:/var/www/msmv
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./../:/var/www/msmv
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: symf0ny
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    ports:
    - "3333:3306"
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbit-node-1
    ports:
      - 60005:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
