version: '2'
services:
  php:
    build: ./php-fpm
    env_file:
      - ./../.env
    volumes:
      - ./../:/var/www/msmv
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./../:/var/www/msmv
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: mydungeon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test

    ports:
    - "5432:5432"

  mercure:
    image: dunglas/mercure
    ports:
      - 3000:80
    environment:
      - JWT_KEY=symfonyBlogJwtToken
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=http://localhost
      - DEBUG=1